export const USER_SIGN_UP_REQUEST = 'USERS_SIGN_UP_REQUEST';
export const USER_SIGN_UP_REQUEST_SUCCEED = 'USERS_SIGN_UP_REQUEST_SUCCEED';
export const USER_SIGN_UP_REQUEST_FAILED = 'USERS_SIGN_UP_REQUEST_FAILED';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_REQUEST_SUCCEED = 'USER_LOGIN_REQUEST_SUCCEED';
export const USER_LOGIN_REQUEST_FAILED = 'USER_LOGIN_REQUEST_FAILED';

export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
